### ISSUE TITLE
Lazy loading of records

### ISSUE THREAD

**Issue by bibendi** [byroot/frozen_record#29]
Hey!

First of all, thanks for your gem!

This change https://github.com/byroot/frozen_record/commit/64871cb70bac5be503d51599db60ea04882e6dfe have broken our app, because of our custom backend have nontrivial records loader using dependencies related to ActionView and so on which are not fully loaded at application boot time. And either the application boot time is increased too. So my question is - what do you this about adding an option to a configuration which will be taken into account when this initializer is executed?

**Comment by byroot** [comment]
You can easily disable that behavior (even though I'd advise against it, but that's your call, I'll assume you know what you are doing).

So to disable it on a per model basis:

```ruby
class MyModel < FrozenRecord::Base
  def self.eager_load!
    # noop
  end
end
```

And to entirely disable it:

```ruby
# config/application.rb
initializer :disable_frozen_record_eager_load do |app|
  app.config.eager_load_namespaces.delete(FrozenRecord)
end
```

NB: I wrote both example from memory, I might have made a typo or something.

Hope this help (closing because I believe I answered, but if you are still stuck feel free to continue posting).
